name: Lint and Test Python Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pylint pytest

      - name: Run Pylint
        run: |
          pylint **/*.py --exit-zero
  
  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r pipeline/requirements.txt
          pip install pytest-cov
      
      - name: Run Pytest
        run: |
          pytest --disable-warnings -q
        
